// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// code.cpp
void fun();
extern "C" SEXP _tfdown_fun() {
  BEGIN_CPP11
    fun();
    return R_NilValue;
  END_CPP11
}
// code.cpp
int version();
extern "C" SEXP _tfdown_version() {
  BEGIN_CPP11
    return cpp11::as_sexp(version());
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_tfdown_fun",     (DL_FUNC) &_tfdown_fun,     0},
    {"_tfdown_version", (DL_FUNC) &_tfdown_version, 0},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_tfdown(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
